name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]


permissions:
  pull-requests: write
  issues: write
  contents: read


jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install anthropic PyGithub

      - name: Download reviewer script
        run: |
          curl -o reviewer.py https://raw.githubusercontent.com/Piya-1803/ai-code-reviewer/main/codereview.py

      - name: Run AI Code Reviewer
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
        run: python reviewer.py